sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
  - '6'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
install: ~/.yarn/bin/yarn
script: ~/.yarn/bin/yarn run test
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - ~/.yarn/bin/yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
